spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatisplus_db?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource  #使用druid数据源
  main:
    banner-mode: off  #将控制台的spring图标去除

#开启mp的日志（输出到控制台）
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false  #将控制台的batisplus图标去除
    db-config:
      id-type: assign_id     #进行id的全局配置
      table-prefix: tbl_     #将每一个实体类的类名前加上 tbl_
      logic-delete-field: deleted   #提供需要逻辑删除的字段
      logic-not-delete-value: 0
      logic-delete-value: 1



